#pragma once

namespace Graphics
{
	enum TextureFilter
	{
		POINT,
		LINEAR,
		ANISOTROPIC,
		LINEAR_MIP_POINT,
		POINT_MIP_LINEAR,
		MIN_LINEAR_MAG_POINT_MIP_LINEAR,
		MIN_LINEAR_MAG_POINT_MIP_POINT,
		MIN_POINT_MAG_LINEAR_MIP_LINEAR,
		MIN_POINT_MAG_LINEAR_MIP_POINT
	};
}
